//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TrainOps.rc
//
#define IDR_MANIFEST                    1
#define RT_MANIFEST                     24
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_TRAINOTYPE                  129
#define IDD_CARTYPES_DIALOG             130
#define IDD_CARS_DIALOG                 131
#define IDB_FOLDERS                     134
#define IDD_EDITCARDIALOG               135
#define IDD_LOCATIONDIALOG              136
#define IDD_SIDINGSDIALOG               137
#define IDD_SIDINGDETAILDIALOG          138
#define IDD_INDUSTRYDIALOG              139
#define IDD_COMMODITIESDIALOG           140
#define IDD_INDUSTRYDETAILDIALOG        141
#define IDD_INDUSTRYCARDETAILDIALOG     142
#define IDD_EDITCOMMODITYDIALOG         143
#define IDD_LOCOMOTIVEDIALOG            144
#define IDD_LOCATIONDETAILDIALOG        145
#define IDD_PREFDIALOG                  146
#define IDD_ROUTESDIALOG                147
#define IDD_EDITTRAIN                   147
#define IDD_TRAINSDIALOG                149
#define IDD_RUNTRAINSDIALOG             151
#define IDD_DATEDIALOG                  152
#define IDD_TERMINATETRAINDIALOG        153
#define IDD_CABOOSEDIALOG               155
#define IDD_CABOOSEDETAILDIALOG         156
#define IDD_CARLOCATIONTRAINSDIALOG     157
#define IDD_TRAINDETAILDIALOG           158
#define IDD_PHYSICAL_LAYOUT_DIALOG      159
#define IDR_LOCATIONMENU                160
#define IDR_SIDINGMENU                  161
#define IDR_INDUSTRYMENU                162
#define IDR_NEWLOCATIONMENU             163
#define IDD_DEBUGDIALOG                 164
#define IDD_CARTYPE_DETAIL_DIALOG       165
#define IDD_FINDDATABASE_DIALOG         166
#define IDD_CARSLIST_DIALOG             167
#define IDD_PDFVIEW_DIALOG              168
#define IDB_SPLASH                      182
#define IDD_MANAGELICENSEDIALOG         186
#define IDD_INDUSTRYDETAILDIALOG_CARS   187
#define IDD_INDUSTRYDETAILDIALOG_COMMODITIES 188
#define IDD_EQUIPMENTLOCATIONDIALOG     198
#define IDD_NEWVERSIONDIALOG            200
#define IDD_EQUIPMENTTRACKINGDIALOG     201
#define IDD_INDUSTRYUSAGEDIALOG         202
#define IDD_EQUIPMENTNOTFOUNDDIALOG     203
#define IDR_EQUIPMENTNOTFOUNDMENU       204
#define IDD_LOCOMOTIVEDETAILDIALOG      206
#define IDD_SCHEDULEDTRAINSREPORTSDIALOG 207
#define IDD_INDUSTRYCARORDERSDIALOG     208
#define IDM_TERMINATETRAINMENU          210
#define IDD_TERMINATENEWLOCATIONDIALOG  211
#define IDC_CARTYPE_LIST                1000
#define IDC_ADD_BUTTON                  1001
#define IDC_DELETE_BUTTON               1002
#define IDC_CARTYPE_ID                  1003
#define IDC_CARTYPE_DESCRIPTION         1004
#define IDC_EDIT_BUTTON                 1005
#define IDC_ADDCARS                     1007
#define IDC_CARTYPE_COMBO               1008
#define IDC_ADDCARS_QUAN                1009
#define IDC_CARTYPE_REPORTINGMARKS      1010
#define IDC_CARTREE                     1011
#define IDC_LOCATIONLIST                1012
#define IDC_ADDBUTTON                   1013
#define IDC_DELBUTTON                   1014
#define IDC_DELETEBUTTON                1014
#define IDC_REMOVEBUTTON                1014
#define IDC_SIDINGSTREE                 1015
#define IDC_EDITBUTTON                  1016
#define IDC_LOCATIONCOMBO               1017
#define IDC_SIDINGNAME                  1018
#define IDC_CAPACITY                    1019
#define IDC_END                         1020
#define IDC_ENDS                        1021
#define IDC_DIRECTION                   1022
#define IDC_DIRECTION2                  1023
#define IDC_INDUSTRYTREE                1023
#define IDC_RADIO5                      1024
#define IDC_COMMODITIESTREE             1024
#define IDC_INDUSTRYNAME                1025
#define IDC_SIDINGCOMBO                 1026
#define IDC_CARSGROUP                   1029
#define IDC_COMMODITIESGROUP            1030
#define IDC_CARLISTIN                   1031
#define IDC_COMMODITIESINLIST           1032
#define IDC_CARLISTOUT                  1033
#define IDC_LOADEMPTY                   1034
#define IDC_COMMODITIESOUTLIST          1034
#define IDC_QUANHIGH                    1035
#define IDC_OFFLAYOUTTIME               1035
#define IDC_QUANLOW                     1036
#define IDC_COMMODITYLIST               1036
#define IDC_PERCENT                     1037
#define IDC_COMMODITYNAME               1037
#define IDC_CARTYPES                    1038
#define IDC_REPORTINGMARKS              1039
#define IDC_CARNUMBER                   1040
#define IDC_LOCOLIST                    1040
#define IDC_NUMBER                      1041
#define IDC_ROADNAME                    1042
#define IDC_CARCAPACITY                 1043
#define IDC_CLEAR                       1044
#define IDC_SAVEBUTTON                  1046
#define IDC_NEWBUTTON                   1046
#define IDC_DESCRIPTION                 1047
#define IDC_ACTIVE                      1048
#define IDC_LOCATIONNAME                1049
#define IDC_EXPANDALL                   1050
#define IDC_COLLAPSEALL                 1051
#define IDC_LOADEMPTYTEXT               1051
#define IDC_RRNAME                      1052
#define IDC_CARLENGTH                   1055
#define IDC_ISYARD                      1056
#define IDC_WEIGHT                      1056
#define IDC_EMPTIES                     1057
#define IDC_ROUTELIST                   1058
#define IDC_AVAILABLELOCATIONLIST       1059
#define IDC_ROUTELOCATIONLIST           1060
#define IDC_INDUSTRIESGROUP             1064
#define IDC_UPBUTTON                    1065
#define IDC_DOWNBUTTON                  1066
#define IDC_INDUSTRYLIST                1067
#define IDC_CREATEBUTTON                1068
#define IDC_SIDINGLIST                  1068
#define IDC_LOCALSWITCHER               1069
#define IDC_ROUTENAME                   1070
#define IDC_ROUTECODE                   1071
#define IDC_CLEARBUTTON                 1072
#define IDC_DELETEROUTEBUTTON           1073
#define IDC_TRAINSLIST                  1074
#define IDC_ROUTECOMBO                  1075
#define IDC_REVERSE                     1076
#define IDC_TRAINNAME                   1077
#define IDC_TRAINID                     1078
#define IDC_TRAINLIST                   1081
#define IDC_RUNNINGTRAINSLIST           1082
#define IDC_TERMINATEBUTTON             1083
#define IDC_BUILDTRAINBUTTON            1084
#define IDC_SWITCHLISTBUTTON            1085
#define IDC_TRAINDETAILBUTTON           1086
#define IDC_FORM19BUTTON                1087
#define IDC_BADORDERBUTTON              1088
#define IDC_SCROLLTEXT                  1090
#define IDC_DATE                        1091
#define IDC_TRAIN                       1092
#define IDC_LOCATION                    1093
#define IDC_LOCATIONFROM                1093
#define IDC_COMMODITY                   1094
#define IDC_ADVANCED                    1095
#define IDC_TEXT1                       1096
#define IDC_TEXT2                       1097
#define IDC_TEXT3                       1098
#define IDC_TEXT4                       1099
#define IDC_TEXT5                       1100
#define IDC_RANDOMIZE                   1101
#define IDC_INDUSTRYFROM                1101
#define IDC_CARLOCATIONS                1102
#define IDC_TEXT6                       1102
#define IDC_SIDINGFROM                  1103
#define IDC_ADVACNCE                    1104
#define IDC_TEXT7                       1104
#define IDC_TEXT8                       1105
#define IDC_METHOD                      1106
#define IDC_INDUSTRYTO                  1106
#define IDC_RADIO2                      1107
#define IDC_LOCATIONTO                  1107
#define IDC_TEXT9                       1108
#define IDC_SIDINGTO                    1109
#define IDC_TRAINDESCRIPTION            1110
#define IDC_TEXT10                      1110
#define IDC_RESETBUTTON                 1111
#define IDC_TEXT11                      1111
#define IDC_LOCATION1                   1112
#define IDC_TEXT12                      1113
#define IDC_SIDING                      1114
#define IDC_CURRENTDATE                 1121
#define IDC_ADVANCE                     1123
#define IDC_CABOOSELIST                 1125
#define IDC_LENGTH                      1128
#define IDC_REPORTBUTTON                1129
#define IDC_REPORTSORTEDBUTTON          1130
#define IDC_TRAINDETAIL                 1133
#define IDC_EMPTY                       1135
#define IDC_LAYOUT                      1137
#define IDC_TRAINS                      1138
#define IDC_EDITTRAIN                   1139
#define IDC_DELETETRAIN                 1140
#define IDC_NEWLOCATIONBUTTON           1141
#define IDC_NEWSIDINGBUTTON             1142
#define IDC_NEWINDUSTRYBUTTON           1143
#define IDC_EDITLOCATIONBUTTON          1144
#define IDC_EDITSIDINGBUTTON            1145
#define IDC_EDITINDUSTRYBUTTON          1146
#define IDC_NEWTRAIN                    1147
#define IDC_EDITCARBUTTON               1149
#define IDC_RANDOM                      1150
#define IDC_DELETECARBUTTON             1150
#define IDC_DEBUGLIST                   1151
#define IDC_ADDCARBUTTON                1151
#define IDC_PASSENGER                   1153
#define IDC_LICENSING                   1154
#define IDC_LICENSEBUTTON               1155
#define IDC_YOURNAME                    1156
#define IDC_NAMETEXT                    1157
#define IDC_VERSIONTEXT                 1158
#define IDC_CARSLIST                    1159
#define IDC_INSTALL_LICENSE_BUTTON      1160
#define IDC_EDITCARSBUTTON              1164
#define IDC_LOCALINSTRUCTIONS           1165
#define IDC_LOGO                        1167
#define IDC_BROWSE                      1168
#define IDC_REALISTICPRINT              1169
#define IDC_LOCOMOTIVELIST              1170
#define IDC_IGNORERESTRICTIONS          1171
#define IDC_UNLICENSE                   1173
#define IDC_PRINTBUTTON                 1183
#define IDC_BRAVAXVIEW1                 1193
#define ID_CLOSE                        1195
#define IDC_TRAINNOTES                  1196
#define IDC_FOREIGN                     1197
#define IDC_INTERCHANGE                 1198
#define IDC_OUTOFSERVICE                1199
#define IDC_NOTES                       1200
#define IDC_MAINTDATE                   1201
#define IDC_LASTMAINT                   1202
#define IDC_FORMS                       1203
#define IDC_TAB                         1205
#define IDC_RATIO_TEXT                  1206
#define IDC_RATIOERROR                  1207
#define IDC_USAGE_TEXT                  1208
#define IDC_EQUIPMENTTREE               1218
#define IDC_COPYRIGHTTEXT               1222
#define IDC_VIEWREADMEBUTTON            1223
#define IDC_CARDATA                     1227
#define IDC_INDUSTRYDETAIL              1228
#define IDC_RETURNTOCOMBO               1229
#define IDC_INTERCHANGEVIACOMBO         1231
#define IDC_NOTFOUNDTREE                1233
#define IDC_INTERCHANGECHECK            1234
#define IDC_INTERCHANGEVIATEXT          1235
#define IDC_NOTFOUNDGRAPH               1238
#define IDC_REPORTSBUTTON               1241
#define IDC_TRAINSTREE                  1242
#define IDC_INDUSTRYCARORDERTREE        1244
#define IDC_MAXMOVES                    1246
#define IDC_MAXMOVESTEXT                1247
#define IDC_RECALC                      1252
#define ID_CONFIGURE_CARS               32771
#define ID_CONFIGURE_LOCATIONS          32772
#define ID_CONFIGURE_SIDINGS            32773
#define ID_CONFIGURE_INDUSTRIES         32774
#define ID_CONFIGURE_CARTYPES           32775
#define ID_CONFIGURE_COMMODITIES        32776
#define ID_CONFIGURE_LOCOMOTIVES        32777
#define ID_CONFIGURE_CABOOSE            32778
#define ID_RUNTRAINS_RUNTRAINS          32779
#define ID_RUNTRAINS_ENDTRAINS          32780
#define ID_RUNTRAINS_ADVANCEDAY         32781
#define IDM_ROUTES                      32782
#define IDM_TRAINS                      32783
#define ID_FILE_PREFERENCES             32784
#define ID_REPORTS_CARLOCATION          32785
#define ID_REPORTS_TRAINHISTORY         32786
#define ID_REPORTS_CARSNOTFOUND         32787
#define ID_REPORTS_CARLOCATIONREPORTS_CARLOCATIONTRAINS 32788
#define ID_CONFIGURE_PHYSICALLAYOUT     32789
#define ID_LOCATIONMENU_NEWLOCATION     32793
#define ID_LOCATIONMENU_EDITLOCATION    32794
#define ID_LOCATIONNMENU_DELETELOCATION 32795
#define ID_SIDINGMENU_NEWSIDING         32796
#define ID_SIDINGMENU_EDITSIDING        32797
#define ID_SIDINGMENU_DELETESIDING      32798
#define ID_INDUSTRYMENU_NEWINDUSTRY     32799
#define ID_INDUSTRYMENU_EDITINDUSTRY    32800
#define ID_INDUSTRYMENU_DELETEINDUSTRY  32801
#define ID_FILE_NEWDATABASE             32803
#define ID_FILE_SAVEDATABASEAS          32804
#define ID_FILE_FINDDATABASE            32805
#define ID_REPORTS_CARLOCATIONREPORTS_CARLOCATIONSORTEDALL 32806
#define ID_REPORTS_CARLOCATIONSORTED    32807
#define IDM_HELP_MANAGELICENSE          32808
#define IDM_HELP_REGISTER               32809
#define IDM_HELP_TOPICS                 32810
#define IDM_HELP_SENDDB                 32811
#define ID_REPORTS_EQUIPMENTLOCATION    32812
#define ID_REPORTS_EQUIPMENTTRACKING    32813
#define ID_REPORTS_INDUSTRYUSAGE        32814
#define IDM_PRUNETOHERE                 32815
#define ID_HELP_RELEASENOTES            32816
#define ID_REPORTS_CARSNEEDED           32817
#define ID__CHANGELOCATION              32822
#define IDM_HELP_SUPPORT_OPENDATADIRECTORY 32823
#define ID_REPORTS_TRAINBUILDINGFORM    32824
#define DB_SCHEMA                       61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1255
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
